### PR TITLE
New design applied to the sample, updated styles and layout

### PR DESCRIPTION
**Pull request by didiepetrova**

### CODE REVIEW

**Comment by TsvetinaIvanova** [comment]
You can consider making a screenshot from iPhone 5 in the simulator to preserve the previous screenshot size.

**Comment by TsvetinaIvanova** [comment]
Rebase from master to resolve conflicts.

**Comment by TsvetinaIvanova** [comment]
:+1:

**Comment by AntonDobrev** [comment]
Do we need the 	"cordova-plugin-inappbrowser" and 	"cordova-plugin-device" for the sample to run? 

:+1:

**Comment by Mike4o** [comment]
We need the device plugin in order to check the platform before constructing the path of the file.
:+1:

**Comment by didiepetrova** [comment]
The Device and InAppBrowser Plugins are mandatory! :)

**Pull request merged**
